In [2]:
import numpy as np

def test_numpy():
    print("NumPy Test Started...\n")
    
    # Create arrays
    a = np.array([1, 2, 3, 4])
    b = np.array([5, 6, 7, 8])
    
    print("Array a:", a)
    print("Array b:", b)
    
    # Basic operations
    print("\nAddition:", a + b)
    print("Subtraction:", a - b)
    print("Multiplication:", a * b)
    print("Division:", a / b)
    
    # Matrix operations
    mat1 = np.array([[1, 2], [3, 4]])
    mat2 = np.array([[5, 6], [7, 8]])
    
    print("\nMatrix 1:\n", mat1)
    print("Matrix 2:\n", mat2)
    
    print("\nMatrix Multiplication:\n", np.dot(mat1, mat2))
    
    # Statistics
    print("\nMean of a:", np.mean(a))
    print("Sum of a:", np.sum(a))
    print("Max of a:", np.max(a))
    print("Min of a:", np.min(a))
    
    print("\nNumPy Test Completed Successfully!")


In [3]:
test_numpy()

NumPy Test Started...

Array a: [1 2 3 4]
Array b: [5 6 7 8]

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Mean of a: 2.5
Sum of a: 10
Max of a: 4
Min of a: 1

NumPy Test Completed Successfully!


In [5]:
a=float(input("enter number 1"))
b=float(input("enter number 2"))
operation=input("press +,-,*,/")
if operation=='+':
    print(a+b)
elif operation=='-':
    print(a-b)
elif operation=='*':
    print(a*b)  
elif operation=='/':
    print(a/b)
else :
    print("invalid operator")


-15.0
